<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mutagen.Bethesda.Skyrim" Version="0.53.1" />
    <PackageReference Include="Mutagen.Bethesda.Synthesis" Version="0.35.5" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NiflySharp">
      <HintPath>libs\NiflySharp.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
