using BijinAIOPathcer.Patchers;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Cache.Internals.Implementations;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Noggog;
using System.Collections.Generic;

namespace BijinAIOPathcer
{
    public class Program
    {
        public static Lazy<Settings.Settings> settings = null!;
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "YourPatcher.esp")
                .SetAutogeneratedSettings("Settings", "settings.json", out settings)
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Constants.BasePath = state.DataFolderPath + "\\meshes\\";



            string sourcePluginName = "Bijin AIO.esp";
            ModKey sourceModKey = ModKey.FromNameAndExtension(sourcePluginName);


            var linkCacheConnectedToLoadOrder = state.LoadOrder.ToImmutableLinkCache();
            if (state.LoadOrder.TryGetValue(sourceModKey) is { Mod: not null } sourceMod)
            {
                ModKey skyrimModKey = ModKey.FromNameAndExtension("Skyrim.esm");
                ExtendedList<FormLink<IRaceGetter>> additionalRaces = [];
                foreach (uint key in Constants.AdditionalRaceIds)
                {
                    Constants.additionalRaces.Add(new FormLink<IRaceGetter>(new FormKey(skyrimModKey, key)));
                }
                Constants.defaultRace = new FormLinkNullable<IRaceGetter>(new FormKey(skyrimModKey, 0x000019));

                NpcPatcher.Apply(state, linkCacheConnectedToLoadOrder, sourceMod.Mod);
                HeadPartPatcher.Apply(state, sourceMod.Mod);
                BodyMeshPatcher.Apply(state, sourceMod.Mod);
                TextureSetPatcher.Apply(state, sourceMod.Mod);
            }else{
                Console.WriteLine("\n================== Error ===================\n");
                Console.WriteLine("Bijin AIO.esp was not found. Please confirm that Bijin Fixes (AIO or Separate) has been installed, and ensure that the corresponding esp is loaded.");
                Console.WriteLine("\n");
                throw new Exception();
            }
            



            string valericaPluginName = "Valerica.esp";
            ModKey valericaModKey = ModKey.FromNameAndExtension(valericaPluginName);
            if (state.LoadOrder.TryGetValue(valericaModKey) is { Mod: not null } valericaMod)
            {
                NpcPatcher.Apply(state, linkCacheConnectedToLoadOrder, valericaMod.Mod);
                HeadPartPatcher.Apply(state, valericaMod.Mod);
                BodyMeshPatcher.Apply(state, valericaMod.Mod);
                TextureSetPatcher.Apply(state, valericaMod.Mod);
            }




            string SeranaPluginName = "Serana.esp";
            ModKey SeranaModKey = ModKey.FromNameAndExtension(SeranaPluginName);
            if (state.LoadOrder.TryGetValue(SeranaModKey) is { Mod: not null } SeranaMod)
            {
                NpcPatcher.Apply(state, linkCacheConnectedToLoadOrder, SeranaMod.Mod);
                HeadPartPatcher.Apply(state, SeranaMod.Mod);
                BodyMeshPatcher.Apply(state, SeranaMod.Mod);
                TextureSetPatcher.Apply(state, SeranaMod.Mod);
            }
        }
    }
}
